.TH dreamchess 6 2014-10 "DreamChess 0.2.1"
.SH NAME
dreamchess \- User interface for XBoard-compatible chess engines

.SH SYNOPSIS
.BI "dreamchess [" options "]

.SH DESCRIPTION
DreamChess is a user interface for XBoard-compatible chess engines. DreamChess comes with its own simple engine called Dreamer, but you can use stronger engines such as GNU Chess or Crafty.

.SH OPTIONS

.TP
.B "\-\-help, \-h"
Show help and exit.

.TP
.B "\-\-list-drivers, \-l"
List all available drivers.

.TP
.BI "\-\-ui " driver ", \-u" driver
Specifies which user interface driver should be used. User interface drivers take care of both display output and user input.

.TP
.B "\-\-fullscreen, \-f"
Enable fullscreen

.TP
.BI "\-\-width " num ", \-W" num
Set screen width

.TP
.BI "\-\-height " num ", \-H" num
Set screen height

.TP
.BI "\-\-1st-engine " engine ", \-1" engine
Name of first chess engine.  Defaults to 'dreamer'.

.TP
.BI "\-\-verbose " level ", \-v" level
Sets verbosity level. 0: Silent, 1: Errors only (default), 2: Errors and warnings only, 3: All.
