set(CPACK_PACKAGE_VERSION ${PROJECT_VERSION})
set(CPACK_PACKAGE_VENDOR DreamChess)
set(CPACK_PACKAGE_INSTALL_DIRECTORY ${PROJECT_NAME})
set(CPACK_RESOURCE_FILE_LICENSE ${CMAKE_SOURCE_DIR}/LICENSE.txt)
set(CPACK_WIX_UPGRADE_GUID 11F270FA-4B99-4398-B2EC-530643FCD4DF)
set(CPACK_WIX_TEMPLATE ${CMAKE_SOURCE_DIR}/dist/wix/WIX.template.in)
set(CPACK_WIX_PRODUCT_ICON ${CMAKE_SOURCE_DIR}/dreamchess/src/win32.ico)

include(CPack)
